
[master]
master ansible_host=52.90.52.107 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/newkey.pem

[workers]
node1 ansible_host=3.82.56.122 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/newkey.pem
node2 ansible_host=52.202.214.186 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/newkey.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3

