- name: Disable swap
  command: swapoff -a

- name: Remove swap from fstab
  replace:
    path: /etc/fstab
    regexp: '^.*swap.*$'
    replace: ''

# ----------------------------
# containerd setup
# ----------------------------

- name: Install containerd
  apt:
    name: containerd
    state: present
    update_cache: yes

- name: Create containerd config dir
  file:
    path: /etc/containerd
    state: directory

- name: Generate default containerd config
  shell: containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml

# 🔥 أهم تعديل
- name: Enable SystemdCgroup
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'

- name: Restart containerd
  systemd:
    name: containerd
    state: restarted
    enabled: yes

# ----------------------------
# CNI plugins
# ----------------------------

- name: Download CNI plugins
  get_url:
    url: https://github.com/containernetworking/plugins/releases/download/v1.4.0/cni-plugins-linux-amd64-v1.4.0.tgz
    dest: /tmp/cni.tgz

- name: Create CNI directory
  file:
    path: /opt/cni/bin
    state: directory
    mode: '0755'

- name: Extract CNI plugins
  unarchive:
    src: /tmp/cni.tgz
    dest: /opt/cni/bin
    remote_src: yes